#============================ Omer Kara - Personal =============================
#================================== Netlify ====================================
#=============================== netlify.toml ==================================

#===============================================================================
# Configuration: Netlify.
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).
#===============================================================================
[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.110.0"

[context]
  [context.branch-deploy]
    command = "hugo -F -b $DEPLOY_PRIME_URL"

  [context.deploy-preview]
    command = "hugo -F -b $DEPLOY_PRIME_URL"

[context.production]
  [context.production.environment]
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"
